#!/usr/bin/env bash

which node &> /dev/null || { echo "you need to install node.js"; exit 1; }
which npm &> /dev/null || { echo "you need to install npm"; exit 1; }

[[ ! -d node_modules/ ]] && npm install

wrapper_timeout=false

echo "starting watcher..."
while true; do
    timeout 300 node watcher.js "${wrapper_timeout}"
    if (( $? != 124 )); then
        sleep 5
        wrapper_timeout=false
    else
        wrapper_timeout=true
    fi
done
