#!/usr/bin/env bash

which node &> /dev/null || { echo "you need to install node.js"; exit 1; }
which npm &> /dev/null || { echo "you need to install npm"; exit 1; }

[[ ! -d node_modules/ ]] && npm install

echo "starting watcher..."

while ! node watcher.js; do
    sleep 5
done
